name: "Publish Issue to Nostr"
branding:
  icon: send
  color: purple
description: "Publish details about a GitHub issue to Nostr"
inputs:
  token:
    description: "GitHub token for authentication"
    required: true
  repo:
    description: 'Repository name in the format "owner/repo"'
    required: true
  issue_number:
    description: "Issue number to log details for"
    required: true
  nsec:
    description: Private key nsec format
    required: true
  kind:
    description: Kind
    required: false
    default: "1"
  tags:
    description: Tags stringified JSON list
    required: false
    default: "[]"
  relays:
    description: Relay URLs `wss://...` (separated by `,`) stringified JSON list
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "21"
    - name: Install dependencies
      run: npm install
      shell: bash
    - name: Run JavaScript function
      run: node --experimental-websocket ${{ github.action_path }}/dist/index.js
      shell: bash
